### ISSUE TITLE
Can't install on windows 11

### ISSUE THREAD

**Issue by shfxia** [WRKampi/extensisq#2]
I try to install extensisq on windows using pip, getting the following error:
```text
>pip install extensisq 
Collecting extensisq
  Using cached extensisq-0.4.0.tar.gz (65 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Alfre\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Alfre\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Alfre\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Alfre\AppData\Local\Temp\pip-build-env-nu5_8sep\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])       
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^       
        File "C:\Users\Alfre\AppData\Local\Temp\pip-build-env-nu5_8sep\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\Alfre\AppData\Local\Temp\pip-build-env-nu5_8sep\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)      
        File "C:\Users\Alfre\AppData\Local\Temp\pip-build-env-nu5_8sep\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
      UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 8564: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.   
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
System: Windows 11 22621.1992
Python: 3.11.3
pip: 23.2.1

**Comment by WRKampi** [comment]
Strange. I'm not able to look into this issue soon. I don't know what "File "<string>", line 4, in <module>" is. You could try to install with a different version of pip, or with conda. I'll get back to this later.

**Comment by shfxia** [comment]
Yes, I can install it with conda.

**Comment by WRKampi** [comment]
Hi shfxia,

Thanks for reporting the issue and good to hear that the conda install did work for you. I hope you like extensisq.

I tried to reproduce the error using the same python and pip version that you have, but that did not lead to a error.  Maybe there is an incompatibility with the wheel package used by pip. My environment uses wheel version 0.38.4. Do you know which version you have used?
